### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by 0atman** [jlumpe/obsidian-spacekeys#1]
Just a note to say thank you so much for making this plugin, I work inside Obsidian all day every day, and this is going to DRAMATICALLY improve my quality of life!

Before, I had been been half-baking which-key functionality with the following obsidian-vimrc config:

```vimrc
" SPACE MENU (kinda!)
unmap <Space>
exmap palette obcommand command-palette:open
nmap <Space><Space> :palette<cr>

" jump to symbols
exmap "qsymbols darlal-switcher-plus:switcher-plus:open-symbols-active"
nmap <Space>ss :qsymbols<cr>
```

But 1. there's no UI, missing the discoverability of a which-key system, and 2. Actions with two colons in the path don't seem to work. BUT THEY DO IN YOUR PLUGIN! :tada:   

```yaml
  s:
    description: Search
    items:
      s: darlal-switcher-plus:switcher-plus:open-symbols-active
```

I'm going to migrate over all of my nvim bindings - Thank you so much again! :heart:
