### ISSUE TITLE
[FR] Support `file:` keyword

### ISSUE THREAD

**Issue by Moyf** [jlumpe/obsidian-spacekeys#7]
For instance, allowing users use this rule:

```yaml
  w:
    description: Specific Note
    file: notename
```

To open `notename.md` file?
Or, furthermore, also support `folder: Path/To/Folder` to locate in folder in File Explorer?

That feat would expand the use cases a lot!  :)
